.rule_tag: &rule_tag
  if: "$CI_COMMIT_TAG"

.rule_tag_manual: &rule_tag_manual
  <<: *rule_tag
  when: manual
  allow_failure: true

.rule_default_branch: &rule_default_branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.rule_default_branch_manual: &rule_default_branch_manual
  <<: *rule_default_branch
  when: manual
  allow_failure: true

.rule_mr: &rule_mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.rule_mr_manual: &rule_mr_manual
  <<: *rule_mr
  when: manual
  allow_failure: true

.rule_web: &rule_web
  if: '$CI_PIPELINE_SOURCE == "web"'

.rule_web_manual: &rule_web_manual
  <<: *rule_web
  when: manual
  allow_failure: true

.rules_always: &rules_always
  - *rule_tag
  - *rule_default_branch
  - *rule_mr
  - *rule_web

.rules_manual: &rules_manual
  - *rule_tag_manual
  - *rule_default_branch_manual
  - *rule_mr_manual
  - *rule_web_manual

.rules_only_tags: &rules_only_tags
  - *rule_tag

.rules_not_tags: &rules_not_tags
  - *rule_default_branch
  - *rule_mr
  - *rule_web

default:
  image: mcr.microsoft.com/dotnet/sdk:10.0

stages:
  - build
  - test
  - pack
  - publish

include:
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/version/version-calc@v1.2.0
    inputs:
      rules: *rules_always
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-restore@2
    inputs:
      before_script:
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
        - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
      rules: *rules_always
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-build@2
    inputs:
      rules: *rules_only_tags
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-artifacts@2
    inputs:
      name: "dotnet Build+Test"
      stage: test
      rules: *rules_not_tags
      before_script:
        - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
      build: true
      test: true
      test_coverage: true
      test_filter: "/[(Category!=System)&(Category!=Integration)&(Category!=Interoperability)]"
  - project: 'vicione-oss/tooling/templates'
    file: '/CI-Templates/v2/dotnet.yml'
  - project: 'vicione-oss/tooling/ci-templates'
    file: '/project/v1/dotnet.yml'

Push OPCUA Client binaries:
  extends: .dotnet-release-raw-rids
  stage: publish
  rules:
    - <<: *rule_tag
      variables:
        SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-staging'
    - *rule_default_branch_manual
    - *rule_mr_manual
    - *rule_web_manual
  variables:
    SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-dev'
    USER: ${Raw_User_RW_JFrog}
    PASSWORD: ${Raw_PW_RW_JFrog}
    PROJECT: 'src/OpcUa.Client/OpcUa.Client.csproj'
    DST_DIRECTORY: 'fbs/ViciOne.Suite.DataPort.OpcUa.Client'
    METADATA_FILE: 'src/OpcUa.Client/metadata.json'
    METADATA_VERSION_FILE: 'VERSION'
    METADATA_MIN_VERSION_FILE: 'VERSION_CORE'
    METADATA_MIN_VERSION_KEY: 'MinCoreVersion'
  before_script:
    - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
    - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  after_script:
    - !reference [ .push-metadata ]

Push OPCUA Server binaries:
  extends: .dotnet-release-raw-rids
  stage: publish
  rules:
    - <<: *rule_tag
      variables:
        SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-staging'
    - *rule_default_branch_manual
    - *rule_mr_manual
    - *rule_web_manual
  variables:
    SERVER: 'https://ifm.jfrog.io/artifactory/vicione-suite-dev'
    USER: ${Raw_User_RW_JFrog}
    PASSWORD: ${Raw_PW_RW_JFrog}
    PROJECT: 'src/OpcUa.Server/OpcUa.Server.csproj'
    DST_DIRECTORY: 'fbs/ViciOne.Suite.DataPort.OpcUa.Server'
    METADATA_FILE: 'src/OpcUa.Server/metadata.json'
    METADATA_VERSION_FILE: 'VERSION'
    METADATA_MIN_VERSION_FILE: 'VERSION_CORE'
    METADATA_MIN_VERSION_KEY: 'MinCoreVersion'
  before_script:
    - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
    - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  after_script:
    - !reference [ .push-metadata ]

Publish binaries:
  extends: .dotnet-release-public
  stage: publish
  needs:
    - Push OPCUA Client binaries
    - Push OPCUA Server binaries
