<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpcUa.Client\OpcUa.Client.csproj" />
  </ItemGroup>

</Project>
